#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    api-web-80-http:
      entrypoints:
        - http-8000
      rule: HostRegexp(`^api\.ddev\.site$`)
      
      service: "api-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "api-redirectHttps"
    api-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^api\.ddev\.site$`)
      
      service: "api-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "api-redirectHttps"
    
    
    
    api-web-80-https:
      entrypoints:
        - http-8443
      rule: HostRegexp(`^api\.ddev\.site$`)
      
      service: "api-web-80"
      ruleSyntax: v3
      
      tls: true
      
    api-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^api\.ddev\.site$`)
      
      service: "api-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    api-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    api-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-api-web:80
        
    api-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-api-web:8025
        
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/api.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/api.key